version: "3"

services:
  postgres_db:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - 5432:5432
    
    env_file:
      config/.env
    
    volumes:
      - postgres_db_data:/var/lib/postgresql/data/

volumes:
  postgres_db_data: